#-------------------------------
# General Site Settings

title: Lifestream
description: Making your day fluent

background-image-header: 'lifestream_header.jpg'
background-image-footer: 'lifestream_footer.jpg'

menu:
- {name: Appliances, url: '#appliances'}
- {name: Contact, url: '#contact'}


#-------------------------------
# Appliance Section

appliances:
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Washing Machine, folder: 'appliance_01'}
