# General Site Settings

title: Lifestream
description: Making your day fluent

background-image-header: 'lifestream_header.jpg'
background-image-footer: 'lifestream_footer.jpg'

menu:
- {name: Appliances, url: '#appliances'}
- {name: Contact, url: '#contact'}



# Appliance Section

appliances:
- {name: Washing Machine, folder: 'appliance_01'}
- {name: Dishwasher, folder: 'appliance_02'}
- {name: Oven, folder: 'appliance_03'}
- {name: Hi-Fi, folder: 'appliance_04'}
- {name: Lighting, folder: 'appliance_05'}
- {name: Hot Water, folder: 'appliance_06'}
- {name: Central Heating, folder: 'appliance_07'}
